In [84]:
# impport libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import re
import nltk

In [85]:
# load data
data = pd.read_csv("D:/D/Machine Learning/data/Classification/Customer Chunk/customer_chunk.csv")
data.head(5)

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Age,City,PostalCode,Tenure,Contract,...,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn,TotalCharges
0,CUST02497,Female,Yes,Yes,No,87,Los Angeles,10001,43,Month-to-month,...,No phone service,No,No,No,No internet service,Yes,No,No internet service,No,4926.94
1,CUST03898,Male,No,No,No,84,New York,10001,44,Month-to-month,...,No phone service,No,No internet service,Yes,No internet service,No internet service,No internet service,No internet service,Yes,3898.84
2,CUST02000,Male,No,Yes,Yes,88,Phoenix,77001,54,Month-to-month,...,No,No,Yes,No internet service,No internet service,Yes,No internet service,No internet service,No,4775.22
3,CUST02066,Female,No,Yes,No,26,Los Angeles,10001,23,Month-to-month,...,No phone service,No,Yes,No,No,No internet service,No,No,No,1136.89
4,CUST00884,Female,No,No,Yes,48,Phoenix,10001,44,Month-to-month,...,Yes,No,No internet service,No internet service,No internet service,No,No,No internet service,No,2216.72

In [86]:
# check the type of the data
data.dtypes

CustomerID          object
Gender              object
SeniorCitizen       object
Partner             object
Dependents          object
Age                  int64
City                object
PostalCode           int64
Tenure               int64
Contract            object
PaperlessBilling    object
PaymentMethod       object
MonthlyCharges      object
MultipleLines       object
InternetService     object
OnlineSecurity      object
OnlineBackup        object
DeviceProtection    object
TechSupport         object
StreamingTV         object
StreamingMovies     object
Churn               object
TotalCharges        object
dtype: object

In [87]:
# check null values and remove it
data = data.dropna()
data.isnull().sum()

CustomerID          0
Gender              0
SeniorCitizen       0
Partner             0
Dependents          0
Age                 0
City                0
PostalCode          0
Tenure              0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Churn               0
TotalCharges        0
dtype: int64

In [88]:
# convert object number into int
data['TotalCharges'] = data['TotalCharges'].apply(lambda x: int(float(x)) if str(x).strip().replace('.', '', 1).isdigit() else np.nan)
data.head(1)

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Age,City,PostalCode,Tenure,Contract,...,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn,TotalCharges
0,CUST02497,Female,Yes,Yes,No,87,Los Angeles,10001,43,Month-to-month,...,No phone service,No,No,No,No internet service,Yes,No,No internet service,No,4926.0

In [89]:
# processign object data
column_object = data.select_dtypes(include=['object']).columns
column_object

Index(['CustomerID', 'Gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'City', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Churn'],
      dtype='object')

In [90]:
stop_word = set(stopwords.words('english'))
def remove_stopword(txt):
    word_token = word_tokenize(str(txt).lower())
    flt = [word for word in word_token if word.isalpha() and word not in stop_word]
    return " ".join(flt)

def cleaning_text(data):
    dum_data = data
    column_object = dum_data.select_dtypes(include=['object']).columns
    
    # Normalizae text
    for i in column_object:
        dum_data[i] = dum_data[i].str.lower()
        dum_data[i] = dum_data[i].str.strip()

    # Remove punctuation
    for i in column_object:
        dum_data[i] = data[i].str.replace(r'[^\w\s]', '', regex=True)

    # Stop word function
    # for i in column_object:
    #     dum_data[i] = dum_data[i].apply(remove_stopword)
    return dum_data

data = cleaning_text(data)
data =data.dropna()
data.head(3)

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Age,City,PostalCode,Tenure,Contract,...,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn,TotalCharges
0,cust02497,female,yes,yes,no,87,los angeles,10001,43,monthtomonth,...,no phone service,no,no,no,no internet service,yes,no,no internet service,no,4926.0
1,cust03898,male,no,no,no,84,new york,10001,44,monthtomonth,...,no phone service,no,no internet service,yes,no internet service,no internet service,no internet service,no internet service,yes,3898.0
2,cust02000,male,no,yes,yes,88,phoenix,77001,54,monthtomonth,...,no,no,yes,no internet service,no internet service,yes,no internet service,no internet service,no,4775.0

In [92]:
# Label encoding
from sklearn import preprocessing
label = preprocessing.LabelEncoder()

def label_encoding(data):
    dum_data = data
    column = dum_data.select_dtypes(include=['object']).columns
    encoders = {}
    for i in column:
        label = preprocessing.LabelEncoder()
        dum_data[i] = label.fit_transform(dum_data[i])
        encoders[i] = label

    return dum_data

data = label_encoding(data)
data.head(3)

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Age,City,PostalCode,Tenure,Contract,...,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn,TotalCharges
0,2371,0,1,1,0,87,2,10001,43,0,...,1,2,0,0,1,2,0,1,0,4926.0
1,3704,1,0,0,0,84,3,10001,44,0,...,1,2,1,2,1,1,1,1,1,3898.0
2,1905,1,0,1,1,88,4,77001,54,0,...,0,2,2,1,1,2,1,1,0,4775.0